package ru.airlabs.ego.telegram.bot.model;

/**
 * Перечисление для действий пользователя, использующего бот
 *
 * @author Aleksey Gorbachev
 */
public enum BotUserAction {
    START,
    LOGIN,

    REGISTRATION,
    REGISTRATION_USER_NAME,
    REGISTRATION_USER_EMAIL,
    REGISTRATION_USER_PASSWORD,

    INVITATION,
    INVITATION_VACANCY,
    INVITATION_USER_NAME,
    INVITATION_USER_PHONE,
    INVITATION_USER_EMAIL,

    SETTINGS,
    SETTINGS_USERS,
    SETTINGS_USERS_LIST,
    SETTINGS_USERS_ADD,
    SETTINGS_USERS_DELETE,
    SETTINGS_USERS_DELETE_CONFIRM,
    SETTINGS_COMPANY_FIO,
    SETTINGS_COMPANY_PHONE,
    SETTINGS_COMPANY_SITE,
    SETTINGS_COMPANY_ADDRESS,
    SETTINGS_COMPANY_NAME,
    SETTINGS_COMPANY_DESCRIPTION,

    HELP
}
